const products = [
    {
		id: 'OgbBxGA5Lf11',
		code: '99016742',
		name: 'Bicicleta Aro 29 Aço Carbono KSVJ Freios a Disco Suspensão 21V + BRINDE Kit Montagem Bike Profissional 44 Peças',
		brand: 'Ksvj',
		stock: 11,
		images: [
			'/shopee/bicicleta/images/bike.png',
		],
		reviews: {
			total: 335,
			rating: 4.5,
			questions: 7,
		},
		salePrice:  129.90,
		regularPrice: 739.99,
		redirectUrl: "/shopee/bicicleta/",
		offPercentage: 75,
		maxInstallments: 12,
		maxInstallmentsInterest: 1,
	},
					{
		id: 'OgbBxGA5Lf11',
		code: '99016742',
		name: 'Jogo 8 panelas antiaderentes de cerâmica bege + BRINDE Jogo de Talheres de Luxo',
		brand: 'Terrara',
		stock: 24,
		images: [
			'/shopee/pagina-inicial-black/images/kit-panelas.png',
		],
		reviews: {
			total: 429,
			rating: 4.9,
			questions: 7,
		},
		salePrice: 59.90,
		regularPrice: 189.90,
		redirectUrl: "/shopee/panelas-ceramica/",
		offPercentage: 75,
		maxInstallments: 12,
		maxInstallmentsInterest: 1,
	},
			{
		id: 'OgbBxGA5Lf11',
		code: '99016742',
		name: 'Frigideira Wok de Cerâmica Multifunções 8 em 1 à Prova de Explosão + BRINDE Kit Utensílio de silicone',
		brand: 'Modernux',
		stock: 24,
		images: [
			'/shopee/frigideira-ceramica/images/principal-black.jpg',
		],
		reviews: {
			total: 337,
			rating: 4.9,
			questions: 7,
		},
		salePrice:  49.90,
		regularPrice: 179.90,
		redirectUrl: "/shopee/frigideira-ceramica/",
		offPercentage: 75,
		maxInstallments: 12,
		maxInstallmentsInterest: 1,
	},
		{
		id: 'OgbBxGA5Lf11',
		code: '99016742',
		name: 'Escorredor Pro Five + BRINDE Kit Porcelana Oxford c/ 30 peças',
		brand: 'Mistery',
		stock: 24,
		images: [
			'/shopee/escorredor/images/principal-nova.png',
		],
		reviews: {
			total: 741,
			rating: 5.0,
			questions: 7,
		},
		salePrice: 59.90,
		regularPrice: 189.90,
		redirectUrl: "/shopee/escorredor/",
		offPercentage: 75,
		maxInstallments: 12,
		maxInstallmentsInterest: 1,
	},
	{
		id: 'OgbBxGA5Lf11',
		code: '99016742',
		name: 'Frigideira Antiaderente 3 Furos Divisórias + BRINDE Kit 4 Colheres De Bambu',
		brand: 'Cazehn',
		stock: 24,
		images: [
			'/shopee/frigideira-antiaderente/images/principal-black.jpg',
		],
		reviews: {
			total: 569,
			rating: 5.0,
			questions: 7,
		},
		salePrice: 39.90,
		regularPrice: 149.90,
		redirectUrl: "/shopee/frigideira-antiaderente/",
		offPercentage: 75,
		maxInstallments: 12,
		maxInstallmentsInterest: 1,
	},
		{
		id: 'OgbBxGA5Lf11',
		code: '99016742',
		name: 'Kit 10 Potes de Vidro Hermético 370ml + BRINDE Jogo de 6 Copos de Luxo',
		brand: 'Casa Linda',
		stock: 24,
		images: [
			'/shopee/potes-de-vidro/images/potes.png',
		],
		reviews: {
			total: 387,
			rating: 5.0,
			questions: 7,
		},
		salePrice: 39.90,
		regularPrice: 149.90,
		redirectUrl: "/shopee/potes-de-vidro/",
		offPercentage: 75,
		maxInstallments: 12,
		maxInstallmentsInterest: 1,
	},
			{
		id: 'OgbBxGA5Lf11',
		code: '99016742',
		name: 'Fatiador de Legumes e Frutas 3 em 1 + BRINDE Kit 3 Tigelas de Vidro com Tampa',
		brand: 'FatMax',
		stock: 24,
		images: [
			'/shopee/fatiador/images/principal-black.jpg',
		],
		reviews: {
			total: 290,
			rating: 4.8,
			questions: 7,
		},
		salePrice:  39.90,
		regularPrice: 149.90,
		redirectUrl: "/shopee/fatiador/",
		offPercentage: 75,
		maxInstallments: 12,
		maxInstallmentsInterest: 1,
	},
	{
		id: 'OgbBxGA5Lf11',
		code: '99016742',
		name: 'Lava Jato Lavadora Vonder de Alta Pressão LAV1200 + BRINDE Kit Shampoo Profissional Lavagem Detalhada',
		brand: 'Vonder',
		stock: 24,
		images: [
			'/shopee/lavadora/images/airfryer.png',
		],
		reviews: {
			total: 272,
			rating: 4.8,
			questions: 7,
		},
		salePrice:  69.90,
		regularPrice: 259.90,
		redirectUrl: "/shopee/lavadora/",
		offPercentage: 75,
		maxInstallments: 12,
		maxInstallmentsInterest: 1,
	},
			{
		id: 'OgbBxGA5Lf11',
		code: '99016742',
		name: 'Fritadeira sem óleo Airfryer Bella Cuccina + BRINDE Cortador de Batatas',
		brand: 'Bella Cuccina',
		stock: 24,
		images: [
			'/shopee/pagina-inicial-black/images/airfryer.png',
		],
		reviews: {
			total: 315,
			rating: 4.9,
			questions: 7,
		},
		salePrice:  59.90,
		regularPrice: 249.90,
		redirectUrl: "/shopee/airfryer/",
		offPercentage: 75,
		maxInstallments: 12,
		maxInstallmentsInterest: 1,
	},
		{
		id: 'OgbBxGA5Lf11',
		code: '99016742',
		name: 'Furadeira e parafusadeira com maleta e acessórios + BRINDE 2 Baterias Extras e Kit de Chaves Profissional',
		brand: 'NFK',
		stock: 24,
		images: [
			'/shopee/pagina-inicial-black/images/parafusadeira.png',
		],
		reviews: {
			total: 441,
			rating: 4.9,
			questions: 7,
		},
		salePrice:  59.90,
		regularPrice: 249.90,
		redirectUrl: "/shopee/parafusadeira/",
		offPercentage: 75,
		maxInstallments: 12,
		maxInstallmentsInterest: 1,
	},
	{
		id: 'OgbBxGA5Lf11',
		code: '99016742',
		name: 'Secadora de Roupas Fischer Super Ciclo 8KG + Brinde Jogo Toalhas de Banho 4 Peças',
		brand: 'FISCHER',
		stock: 24,
		images: [
			'/shopee/secadora/images/principal-black.jpg',
		],
		reviews: {
			total: 292,
			rating: 4.9,
			questions: 7,
		},
		salePrice:  59.90,
		regularPrice: 249.90,
		redirectUrl: "/shopee/secadora/",
		offPercentage: 75,
		maxInstallments: 12,
		maxInstallmentsInterest: 1,
	},
				{
		id: 'OgbBxGA5Lf11',
		code: '99016742',
		name: 'Kit 6 Facas Profissionais de aço e carbono + BRINDE Afiador de Facas Profissional',
		brand: 'Ueki',
		stock: 24,
		images: [
			'/shopee/pagina-inicial-black/images/kit-facas.png',
		],
		reviews: {
			total: 284,
			rating: 4.9,
			questions: 7,
		},
		salePrice:  29.90,
		regularPrice: 109.90,
		redirectUrl: "/shopee/kit-facas/",
		offPercentage: 75,
		maxInstallments: 12,
		maxInstallmentsInterest: 1,
	},
	    {
		id: 'OgbBxGA5Lf11',
		code: '99016742',
		name: '[PAGUE 2, LEVE 4] Tapete Antiderrapante para Banheiro',
		brand: 'Primar',
		stock: 24,
		images: [
			'/shopee/tapete/images/principal.jpg',
		],
		reviews: {
			total: 168,
			rating: 4.8,
			questions: 7,
		},
		salePrice:  29.90,
		regularPrice: 109.90,
		redirectUrl: "/shopee/tapete/",
		offPercentage: 75,
		maxInstallments: 12,
		maxInstallmentsInterest: 1,
	},
	{
		id: 'OgbBxGA5Lf11',
		code: '99016742',
		name: 'Varal de Chão Roupa Grade 3 Andares Dobrável Portátil + Brinde 30 Cabides antideslizante',
		brand: 'KONTUZ',
		stock: 24,
		images: [
			'/shopee/varal/images/principal-black.jpg',
		],
		reviews: {
			total: 147,
			rating: 4.9,
			questions: 7,
		},
		salePrice:  29.90,
		regularPrice: 109.90,
		redirectUrl: "/shopee/varal/",
		offPercentage: 75,
		maxInstallments: 12,
		maxInstallmentsInterest: 1,
	},
						{
		id: 'OgbBxGA5Lf11',
		code: '99016742',
		name: 'Mini ar condicionado umidificador portátil + BRINDE Luminária de mesa RGB',
		brand: 'Generic',
		stock: 24,
		images: [
			'/shopee/pagina-inicial-black/images/luminaria-ar.png',
		],
		reviews: {
			total: 188,
			rating: 4.9,
			questions: 7,
		},
		salePrice:  29.90,
		regularPrice: 109.90,
		redirectUrl: "/shopee/mini-ar-condicionado/",
		offPercentage: 75,
		maxInstallments: 12,
		maxInstallmentsInterest: 1,
	},
    {
		id: 'OgbBxGA5Lf11',
		code: '99016742',
		name: 'Aplicador e Porta Escova Pasta de Dente com Esterilizador UV Automático + BRINDE Kit 10 Creme Dental Colgate Extracts Carvão',
		brand: 'Glanori',
		stock: 24,
		images: [
			'/shopee/porta-escova/images/principal.jpg',
		],
		reviews: {
			total: 145,
			rating: 4.5,
			questions: 7,
		},
		salePrice:  29.90,
		regularPrice: 109.90,
		redirectUrl: "/shopee/porta-escova/",
		offPercentage: 75,
		maxInstallments: 12,
		maxInstallmentsInterest: 1,
	},
	
];